CREATE TABLE IF NOT EXISTS load_properties
(
   id                  SERIAL,
   mlsnum              SERIAL,
   status              VARCHAR(4000),
   listprice           VARCHAR(4000),
   soldprice           VARCHAR(4000),
   listdate            DATE,
   solddate            DATE,
   expireddate         DATE,
   dom                 VARCHAR(4000),
   dto                 VARCHAR(4000),
   address             VARCHAR(4000),
   city                VARCHAR(4000),
   state               VARCHAR(4000),
   zip                 VARCHAR(4000),
   area                VARCHAR(4000),
   beds                VARCHAR(4000),
   baths               VARCHAR(4000),
   sqft                VARCHAR(4000),
   age                 VARCHAR(4000),
   lotsize             VARCHAR(4000),
   agentname           VARCHAR(4000),
   officename          VARCHAR(4000),
   officephone         VARCHAR(4000),
   showinginstructions VARCHAR(4000),
   remarks             VARCHAR(4000),
   style               VARCHAR(4000),
   level               VARCHAR(4000),
   garage              VARCHAR(4000),
   heating             VARCHAR(4000),
   cooling             VARCHAR(4000),
   elementaryschool    VARCHAR(4000),
   juniorhighschool    VARCHAR(4000),
   highschool          VARCHAR(4000),
   otherfeatures       VARCHAR(4000),
   proptype            VARCHAR(4000),
   streetname          VARCHAR(4000),
   housenum1           VARCHAR(4000),
   housenum2           VARCHAR(4000),
   photourl            VARCHAR(4000)
);

COMMIT;